service:
  http:
    type: NodePort

gitea:
  admin:
    username: tob
    email: ""
    password: ""
  config:
    database:
      DB_TYPE: sqlite3

persistence:
  enabled: true
  storageClass: nfs-client
  size: 10Gi

postgresql-ha:
  enabled: false

postgresql:
  enabled: false

redis-cluster:
  enabled: false

valkey-cluster:
  enabled: false

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"