service:
  http:
    type: NodePort

gitea:
  admin:
    username: tob
    email: ""
    password: ""

persistence:
  enabled: true
  storageClass: nfs-client
  size: 10Gi

postgresql-ha:
  enabled: false

postgresql:
  enabled: true
  primary:
    persistence:
      storageClass: nfs-client
      size: 5Gi